services:
  rancher:
    image: rancher/rancher:latest
    container_name: rke_server
    privileged: true
    volumes:
      - rancher_data:/var/lib/rancher
      - /srv/rancher_certs/cert.pem:/etc/rancher/ssl/cert.pem
      - /srv/rancher_certs/key.pem:/etc/rancher/ssl/key.pem
      - /srv/rancher_certs/cacerts.pem:/etc/rancher/ssl/cacerts.pem
    restart: always
    ports:
      - "443:443"
      - "80:80"

volumes:
  rancher_data:
  rancher_certs:
